name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12.3  # Specify the exact Python version if possible to match local and CI environments
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Install dependencies  # Ensuring all dependencies are installed from a requirements file
        run: pip install -r requirements.txt
      - name: Log environment details  # Logging detailed environment information to debug issues
        run: |
          python -m pip list
          which python
          which mkdocs
      - run: mkdocs gh-deploy --force  # Deploying MkDocs site
