name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'  # Ensure this matches the Python version needed
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt  # Install all dependencies
      - run: mkdocs gh-deploy --force  # Deploy to GitHub Pages
      - name: Log installed packages
        run: pip list
      - name: Log environment paths
        run: |
          echo "Python location: $(which python)"
          echo "MkDocs location: $(which mkdocs)"
